### ISSUE TITLE
Update "assessment review" section of resume review to align with the phone interview page

### ISSUE THREAD

**Issue by wslack** [usds/SME-QA-Website#101]
https://smeqa.usds.gov/hiring-phases/reviewing-resumes/reviewing-sme-notes/ is fairly short on content and should align more with https://smeqa.usds.gov/hiring-phases/phone-assessment-interviews/reviewing-sme-assessments/

**Comment by humancompanion-usds** [comment]
Yeah, I was going to copy some of the salient items from the interview page to the resume review page but didn't want to get into a battle over content straight away. Given that Stephanie wrote the reviewing-sme-notes I figure that's what she wanted.

**Comment by wslack** [comment]
I'm confused on my notes from yesterday; it sounded like we needed some of that content moved over, right?

**Comment by humancompanion-usds** [comment]
@wslack - Yes, but Stephanie wrote that content during the staff meeting and sent it to me which is what is on the page now. The page did not exist at all until this morning.

**Comment by wslack** [comment]
AHA ok - no wonder my notes confused me!
