### ISSUE TITLE
before monday: remove time estimate from 'getting started'

### ISSUE THREAD

**Issue by stephaniefaith** [usds/SME-QA-Website#113]
in the getting started page it says estimated 1 day for a lot of tasks that may take a month- can we remove the time estimate from this page?

**Comment by humancompanion-usds** [comment]
@stephaniefaith - I raised this issue here:
https://github.com/usds/SME-QA/issues/476#issuecomment-555815371

I'd rather we fix this systemically rather than page by page.

**Comment by stephaniefaith** [comment]
i feel like this is helpful on some pages though and not others... but saying 1 day for getting started seems super misleading and makes me somewhat uncomfortable. i ususally tell ppl this is the longest part and coudl take a month to set up
