### ISSUE TITLE
Add mechanism to check links as part of build process

### ISSUE THREAD

**Issue by wslack** [usds/SME-QA-Website#118]
We should have a mechanism to find links that are broken during or after site build.

**Comment by humancompanion-usds** [comment]
Yes! It's annoying that so many toolkit links are broken or keep breaking as we rename or move materials. I have never found a good link checker for Jekyll that doesn't require Java or some other extra dependencies that are onerous for everyone to install. I wonder if @jaredcunha-usds could point me in the right direction here before he rides off into the sunset.

**Comment by wslack** [comment]
Hmmm I just found https://site-scanning.app.cloud.gov/scans/ but not sure it fully applies
