### ISSUE TITLE
Add more detailed information about time commitment/timeline

### ISSUE THREAD

**Issue by wslack** [usds/SME-QA-Website#133]
We got a question this morning about how long the process takes.

I am thinking about creating content to explain how timelines can vary but also taking folks through a "standard" timeline so there are common expectations about the # of months this takes.

**Comment by wslack** [comment]
Assuming:
- 10 SMEs equally splitting up all tasks
- Available for 10 hours/week
- With 100 applicants in resume review
- 40 applicants in a round 1 interview (1 on 1)
- 25 applicants in a round 2 interview (1 on 1)

Each SME will spend:
- 21 hours in workshops and training
    - 16 hours in the job analysis workshop
    - 3 hours in resume review training
    - 2 hours in interview training
- 15 hours doing SME work (assuming 10 SMEs)
    - 1-2 hours performing resume review
    - 8 hours in round 1 interviews
    - 5 hours in round 2 interviews
- with other SME counts:
   - 18 hours (assuming 8)
   - 30 hours (assuming 5)

**Comment by wslack** [comment]
The 8 hours we say now suggests that 200 resumes reviewed by 8 SMEs take 19.2 minutes/resume, which is confusing.

**Comment by wslack** [comment]
@stephaniefaith this is edited and ready for review

**Comment by wslack** [comment]
We sent this to Veta today and Stephanie looked over it. Next step is website-ifying it.

**Comment by wslack** [comment]
Another version:


#### Example Timeline

- Week One: Job analysis workshop
- Week Two: Circulate workshop output, draft job announcement, begin recruitment
- Week Three: Post Job Announcement (until midnight after 100 applicants), SME resume review training
- Week Four: SMEs do resume review
- Week Five: HR reviews notes and sends tiebreakers to other SMEs
- Week Six: HR reviews notes, begins scheduling interviews, and trains SMEs doing Interview 1
- Weeks Seven and Eight: SMEs hold interview 1. HR reviews notes, schedules round 2 interviews, and trains SMEs doing Interview 2.
- Weeks Eight and Nine: SMEs hold interview 2; HR reviews notes
- Weeks Ten and Eleven: HR issues certs; hiring managers hold final placement interviews and tell HR which applicants they want
- Week Twelve: HR sends offers. Applicants confirm or decline within 48 hours. HR creates new certificates with next category for the HM to consider. Repeat process; once hiring manager is done, share certificate with other interested offices at the agency

**Comment by stephaniefaith** [comment]
@wslack Matt and I looked at your math above, and think we can include it on the SME time commitment page at the bottom as a "Plug in your numbers to find out the estimated time commitment for your hiring action" - and then that can link to an excel chart with your formulas above....does that work? what do you think?

**Comment by wslack** [comment]
Works for me! My biggest thing is making our site's numbers more like ranges.

**Comment by wslack** [comment]
The only thing left on this is a low-priority task to create a more "calculator" like thing.

**Comment by humancompanion-usds** [comment]
I created issue #159 for the remaining item here. Closing.
