### ISSUE TITLE
update assessment strategy page

### ISSUE THREAD

**Issue by stephaniefaith** [usds/SME-QA-Website#145]
1) in the illegal section, this phase: "you may choose additional assessment options to measure an applicant's competencies for the position:" needs to say: "depending on the results of job analysis you may include additional assessment hurdles to measure an applicant's competencies."
2) Will confirmed our new illegal section is getting lost. can we try to make the toolkit section intro much shorter? Instead of:
"Use the assessment strategy template to document your assessment strategy for your current hiring action. Make sure you're comfortable with the strategy because you'll finalize some remaining details with SMEs during the job analysis workshop.

In addition to the Assessment strategy template document, download the items in the toolkit, customize them for your hiring action, and include them in your case file. Your assessment strategy is the documentation you provide to auditors who may review your hiring action later.:
can we try:
"Download the items in the toolkit, finalize them with your hiring manager and SMEs, and upload them to your case file before the job announcement is posted. This information will be useful to auditors reviewing this hiring action."

3) let's remove- the authority for SME-QA section here because it just pushes the illegal part down farther. or after all the bullets in the illegal section we can have one line that says "Read more about the authority to use this process in existing OPM guidance." - that links to the other page. I just dont like it as a separate section here pushing everything else down where it gets lost.

4) This page uses both "pass fail " and "pass/fail" - I think we should be consistent with "pass/fail"

5) remove (see page 4) from the last bullet on this page in the illegal section because we shouldn't just reference one thing alone.

**Comment by wslack** [comment]
Done in https://github.com/usds/SME-QA-Website/pull/249
