### ISSUE TITLE
Design icons for SME, HR and HM for timeline graphic in issue #153

### ISSUE THREAD

**Issue by sstrassberg** [usds/SME-QA-Website#154]
Icons to represent SME, HR and HM for https://github.com/usds/SME-QA-Website/pull/153#issuecomment-585914936

**Comment by sstrassberg** [comment]
![HM_icon](https://user-images.githubusercontent.com/48692564/74981664-ad277980-5400-11ea-9d1f-e87f161ca61a.png)
![HR_icon](https://user-images.githubusercontent.com/48692564/74981666-ad277980-5400-11ea-84a5-9673687499cc.png)
![SME_icon](https://user-images.githubusercontent.com/48692564/74981668-adc01000-5400-11ea-8c68-3d0aa80bc7a2.png)
@humancompanion-usds Thoughts?

**Comment by humancompanion-usds** [comment]
The hiring manager and SME ones I get. The HR one is a bit of stretch but, sure. These work. I can incorporate them into the timeline and the service map.

**Comment by sstrassberg** [comment]
@humancompanion-usds Ok, do you want me to add any color? Or I can upload the svg files to the design assets folder.

**Comment by humancompanion-usds** [comment]
Yeah, actually drop the icons in the SME-QA repo in design-assets/icons (you'll have to create the icons directory). Then if you want to update the timeline with them it's here:
https://github.com/usds/SME-QA-Website/blob/master/_mocks/timeline.xd

Just output a 2x png or jpeg when you're done and I'll add it to the site. I will use them for the service map I'm working on as well for consistency.

**Comment by sstrassberg** [comment]
Ok, updated the XD file, and @2x png's are here: 
https://github.com/usds/SME-QA-Website/blob/master/_mocks/timeline-v5.1%402x.png
https://github.com/usds/SME-QA-Website/blob/master/_mocks/timeline-v5%402x.png
