### ISSUE TITLE
Add note to SME selection page

### ISSUE THREAD

**Issue by stephaniefaith** [usds/SME-QA-Website#167]
In SME selection section, add a note that any SME participating CANNOT apply for the job. They will not be allowed to develop test material and then also be an applicant.

**Comment by humancompanion-usds** [comment]
On this page https://smeqa.usds.gov/hiring-phases/getting-started/selecting-smes/ we have that noted in the paragraph below the checklist:

> Once you choose SMEs, they must sign the SME Confidentiality Agreement and agree to protect all testing material, including interview questions and required proficiency levels. They also can’t apply for the position(s) you post for the hiring action.

Do we just need to add that "anyone developing test material (i.e. interview questions) cannot apply for this position"?

**Comment by stephaniefaith** [comment]
I think we should take this sentence out of the paragraph: "They also can’t apply for the position(s) you post for the hiring action." and move it to be one of the guidelines in the checklist above that paragraph: "Not interested in applying to this position at the GS level being advertised for this hiring action or for a future action reusing the work from this job analysis."

**Comment by humancompanion-usds** [comment]
Not being able to apply to a single job is a lot different than never being able to apply to any job that uses those competencies and proficiency levels. What counts as test materials? Is it just interview questions or is it proficiency levels as well? Doesn't that either limit the reuse of job analysis OR potentially limit who would want to be a SME?

**Comment by stephaniefaith** [comment]
test materials = interview questions and proficiency levels since neither are disclosed in the announcement.  If SMEs are at or above the grade level already it shouldnt be an issue. BUT it is an issue if a contractor is asking as a SME who wants to get a fed job. But if the contractor is already a GS15 and it's a GS13 job obviously that's not an issue.   If the contractor is a GS13 and wants to apply for a job that reuses the same criteria in 6 months or a year, they have an advantage bc they helped create the test material creating a conflict.

**Comment by JennNoinaj** [comment]
updated https://smeqa.usds.gov/hiring-phases/getting-started/selecting-smes/
