### ISSUE TITLE
Create generic version of EPA's resume review excel chart and put it on our RR toolkit

### ISSUE THREAD

**Issue by stephaniefaith** [usds/SME-QA-Website#169]
background: EPA created  an awesome excel tool that we can make generic and then add to our website for non-RAT customers.

- [x] make generic version of EPA's excel tool (steph) 

- [ ] review steph's work, then add to our resume review toolkit on our website. (jenn)

**Comment by stephaniefaith** [comment]
[Resume Review Excel Template.xlsx](https://github.com/usds/SME-QA-Website/files/4331776/Resume.Review.Excel.Template.xlsx)

**Comment by JennNoinaj** [comment]
Updated the template to consolidate 3 columns into one and made the drop-down items more generic.

[Resume Review Template.xlsx](https://github.com/usds/SME-QA-Website/files/4417634/Resume.Review.Template.xlsx)

Moving this ticket to Up Next to load it onto the website.

**Comment by wslack** [comment]
This was merged!
