### ISSUE TITLE
update revised competency library with examples of 2 and 4 proficiency levels

### ISSUE THREAD

**Issue by stephaniefaith** [usds/SME-QA-Website#173]
[sample-competencies and 2 and 4 proficiencies.docx](https://github.com/usds/SME-QA-Website/files/4340080/sample-competencies.and.2.and.4.proficiencies.docx)

**Comment by stephaniefaith** [comment]
complete- for  @wslack to review

**Comment by stephaniefaith** [comment]
before we finalize maybe  we should incorporate 1173 from the SME-QA project board (making comp defs active verbs and shorter)

**Comment by stephaniefaith** [comment]
closing this one to finish this task in issue #1173.

**Comment by wslack** [comment]
👍
