### ISSUE TITLE
tweaks needed to the timeline on the website

### ISSUE THREAD

**Issue by stephaniefaith** [usds/SME-QA-Website#174]
Background: I love the graphic we added to the website with the sample timeline, however, it contradicts our guidance in a few places. https://smeqa.usds.gov/hiring-phases/getting-started/timeline/

1. on the time commitment page it says resume review takes 5 hours over 1 week per SME but on the graphic it says to schedule 2 weeks for resume review. i think we should perhaps make the timeline suggest 1 week for resume review.
2. on the timeline page it says week 2 is to prep JOA but our guidance says to do this during the job analysis workshop so maybe week 2 should say "Final Tweaks to JOA and Questions"
3. on the timeline page it says 4 weeks for interviews but i believe our guidance says 3 weeks so each period is two weeks and they overlap.

**Comment by JennNoinaj** [comment]
Finished, see issue #209: https://smeqa.usds.gov/hiring-phases/getting-started/timeline/
