### ISSUE TITLE
Change website section on "phone interviews" to "assessments" and make it clear we don't suggest two phone interviews

### ISSUE THREAD

**Issue by wslack** [usds/SME-QA-Website#181]
Content would come from https://github.com/usds/SME-QA/issues/1262. Will take a fair amount of work to update all of the menus and such.

**Comment by wslack** [comment]
Should also be done with https://github.com/usds/SME-QA/issues/1345

**Comment by wslack** [comment]
Example link: https://github.com/usds/SME-QA-Website/blob/reorg-interviews-to-assessments/pages/phases/phone-assessment-interviews/index.html

**Comment by kbnammacher-usds** [comment]
Just updated this with an initial pass, got to the "assessment strategies" page, will finish seeing what needs to be changed tomorrow.

**Comment by wslack** [comment]
https://github.com/usds/SME-QA-Website/pull/241 has a good chunk of the work done!
