### ISSUE TITLE
Master Ticket Website Updates

### ISSUE THREAD

**Issue by sstrassberg** [usds/SME-QA-Website#198]
### Legend
**U:** Usability (*Major, Minor, Cosmetic*)
**C:** Complexity (*High, Medium, Low*)
**P:** Priority (*Now, Next, Later*)

**1. Provide more info about USA Staffing (i.e. certs)**
*U: Major; C: Low; P: Now*
- [ ]  Jenn to work on SOP's

**2. Redesign Homepage based off research findings**
*U: Minor; C: Medium; P: Now*
- [x]  Shane to work on a few mockup iterations
- [x]  Build prototype
- [ ]  Test prototype
- [ ]  Rinse and repeat

**3. Reorganize info based off research findings**
*U: Minor; C: Medium; P: Now*
*  Confusion that SMEQA is a new process
*U: Minor; C: Low; P: Next*
*  Clarify the category ratings based off of the process
*U: Cosmetic; C: Low; P: Next*
- [ ]  Determine which pages might be able to be condensed/combined
- [ ] Reconfigure formatting for better scanning/readability (i.e. paragraph headings/subheadings, bullets when feasible)
- [ ] Redesign and/or reorganize dropdown menus
- [x] Redesign results page to use side nav for individual agency results; include results graphic

**4. Address the time concern from users**
*U: Cosmetic; C: Low; P: Next*
- [ ] Add updated graphic from github to website (https://github.com/usds/SME-QA-Website/blob/master/_mocks/timeline-v5.1%402x.png)
- [ ] Get feedback from users

**5. Address HR concern about SME participation**
*U: Major; C: Medium; P: Next*
- [ ] Review existing documentation
- [ ] Determine if it can be presented with visuals to support text
- [ ] Create visual
- [ ] Get user feedback

**6. Make sure each resource opens in a new tab**
*U: Minor; C: Low; P: Later*
- [ ]  Determine hierarchy of which resources should be deemable to open in new tab
- [ ] Update code to support this function

**Comment by sstrassberg** [comment]
@JennNoinaj Please take a look at the list above and let me know if you think it's good or what needs to be edited.

**Comment by JennNoinaj** [comment]
add contact info for people to provide feedback on the website

**Comment by sstrassberg** [comment]
Broke #3,4,5 down into singular issues:
https://github.com/usds/SME-QA-Website/issues/272
https://github.com/usds/SME-QA-Website/issues/271
https://github.com/usds/SME-QA-Website/issues/270

Other #'s have already been completed in other issues. Closing this master issue.
