### ISSUE TITLE
add info for Monster Customers to website

### ISSUE THREAD

**Issue by stephaniefaith** [usds/SME-QA-Website#214]
I think this should go on the job announcement page near the USA Staffing SOP which we wrote but is currently lost somewhere on the website- maybe in a PR? 

We should add something like:

"Contact us if you’re a monster customer and we can share their proprietary information on how to make this process work within Monster for SME resume reviews."

**Comment by JennNoinaj** [comment]
Contact us is pending smeqa@omb.eop.gov alias creation

**Comment by JennNoinaj** [comment]
update https://smeqa.usds.gov/hiring-phases/job-announcement/, waiting on alias creation

**Comment by wslack** [comment]
Not doing the alias creation (at least for now)
