### ISSUE TITLE
Provide more information on cost-benefit analysis on the website to help agencies make informed decisions on expected costs per hire

### ISSUE THREAD

**Issue by sharmaneil** [usds/SME-QA-Website#233]
For this page:
https://smeqa.usds.gov/hiring-phases/getting-started/identifying-appropriate-positions/

- We have data on how much running a SMEQA hiring action has cost a couple different agencies in total, per selection, and per accepted offer. This information could be communicated better (likely via a visual). 
- it should be made clear that the first action an agency runs is very likely more expensive than subsequent ones (because of training + material generation), and that subsequent actions are likely cheaper. At the moment, we don't have data on the savings tho
- TODO: consider if we want to factor in USDS costs to these numbers
- TODO: add citations around private-sector costs. 
- TODO: consider if we want to mention that paid recruitment costs are not factored into our numbers

**Comment by wslack** [comment]
Notes:
- We aren't sure about including information about $$$ or "cost" because it will make people think of budgets
- It might be better to discuss this all in terms of time and hours, not as money.

**Comment by kbnammacher-usds** [comment]
We think this should not live on the website, as it could turn people away before they start a convo with us. 

We already merged the PR related to this task.
