### ISSUE TITLE
add picture of job analysis on job analysis workshop page

### ISSUE THREAD

**Issue by stephaniefaith** [usds/SME-QA-Website#237]
![CX picture](https://user-images.githubusercontent.com/3639541/86285409-8fd69900-bbb2-11ea-9d7a-e2fbdbc1ecc4.jpg)
![CMS Picture](https://user-images.githubusercontent.com/3639541/86285419-96651080-bbb2-11ea-8b5e-84a8e3bdeca6.jpg)

the CX one can go here: https://smeqa.usds.gov/hiring-phases/job-analysis/documenting-job-tasks/

and the CMS one can go here: https://smeqa.usds.gov/hiring-phases/job-analysis/converting-job-tasks-to-competencies/

**Comment by wslack** [comment]
Did you get permission to post photos from the first workshop?

**Comment by stephaniefaith** [comment]
no and i dont think we need to do that w/feds; just the public

**Comment by wslack** [comment]
After a folder name fix, this was merged
