### ISSUE TITLE
Improve the Results page

### ISSUE THREAD

**Issue by humancompanion-usds** [usds/SME-QA-Website#268]
The results page is woeful. We've been in a holding pattern waiting on approval to improve the story there. I believe we are close to having clearance to share parts of the final report for the 1st round of pilots, correct @wslack? Once we can do that I'd like to use that content on the results page.

* [x] Get final report cleared
* [x] Move the story captured in the final report onto the results page, translating for good story telling on the web
* [x] Add results from the 2nd round of pilots to the _data file
* [x] Improve the "base" page for each pilot incorporating data, images, and more of what happened with that agency/pilot

**Comment by humancompanion-usds** [comment]
Here is a potential layout from Will for phase 2 pilots that I had not seen in https://github.com/usds/SME-QA/issues/1407:

## User story
- As a stakeholder in OMB or OPM, I want to be able to quickly/easily learn about how the phase 2 pilots improved. 

Possible stories:
- As a member of the press, I want a story about how the White House has improved hiring.

## Proposed structure:
Contents are mostly [on the SME-QA website](https://smeqa.usds.gov/results/), written as a report for new possible pilots. Web content is also put into a one-time word report with additional, non-public content that we can't put on the website.

### Components
- Time to hire results with all pilots compared
- Selection and vacancy data
- Who made it through/demographics
- Cost benefit analysis?
- Technology used (Interim ATOs, paragraphs and screenshots)
  - This page is for stakeholders and press to learn quickly without seeing the "how-to"
  - Just learning what happened and how it worked out.
- Best practices w/ blurbs on written prompts/HireVue, how State did their job analysis. Paragraph summarizing what we learned, what went wrong.
- Summary of user research
  - Balanced overall takes
- No pages on each specific pilot, all data is presented together

### Artifacts ready to go:
- Timeline graphic from Shane
- Neil's graphics

### Artifacts to create (organized)
 - Based on all actions to date, showing typical passing rates of resume review vs various assessments.
 - Cost benefit analysis tool/graph

**Comment by humancompanion-usds** [comment]
Will and I briefly chatted yesterday and so I'm trying to scope and prioritize these changes a bit.

## Results index page
* High level stats
* Summary and link to first round pilots page
* Summary and link to second round pilots page
* Summary and link to gov-wide pilots page
* Assessment and Selection Summary table
* Time to hire comparison of rounds 1 and 2 (HHS & DOI compared to EPA & CMS graphic)

### 1st Round Pilots
* Case studies
  1. By the numbers (aggregate)
  2. What went well including goals and outcomes
  3. Lessons learned
  4. User feedback

### 2nd Round Pilots
* Case studies
  1. By the numbers (aggregate)
  2. What went well including goals and outcomes
  3. Lessons learned
  4. User feedback

### Gov-wide pilots
* Case studies
  1. By the numbers (aggregate)
  2. What went well including goals and outcomes
  3. Lessons learned
  4. User feedback

### Individual agency pages
* Quote
* By the numbers

**Comment by wslack** [comment]
That looks good to me! @stephaniefaith may want to check it as well

**Comment by humancompanion-usds** [comment]
Leaving this open because we could add a lot more to the Round One page once the final report is cleared.

**Comment by stephaniefaith** [comment]
@wslack @sstrassberg i think we're done with all these things maybe?

**Comment by sstrassberg** [comment]
@stephaniefaith I believe so, but @wslack probably has the best insight into this.

**Comment by wslack** [comment]
https://github.com/usds/SME-QA-Website/pull/322 needs to be merged

**Comment by wslack** [comment]
But, there's more to do. The agency pages only do one pilot per page.
