### ISSUE TITLE
add last step for HR to smeqa website

### ISSUE THREAD

**Issue by stephaniefaith** [usds/SME-QA-Website#291]
When we’ve done multiple grades before, even though initial SME resume review is at the GS12 lower level only, the final step before certification was for HR to review resumes of those qualified to make sure there were none who slipped through who didn’t have 1 year of experience at the appropriate level (or who were currently at a lower grade level (GS-11 or below) who wouldn’t qualify for the GS-13).  So SMEs didn’t need to review the resume for the GS-13 quals up front because they used the assessment(s) to determine if qualifications were met at that level and verified it with the resume prior to issuing the certificate.

**Comment by wslack** [comment]
Here's a PR: https://github.com/usds/SME-QA-Website/pull/385

**Comment by stephaniefaith** [comment]
closed- merged
