### ISSUE TITLE
Create six-month check-in summary for website.

### ISSUE THREAD

**Issue by sstrassberg** [usds/SME-QA-Website#323]
We want to add a section to the results page that highlights the long-term effect SME-QA is having. Here is the file: https://github.com/usds/SME-QA/blob/main/user_research/reports/six-month%20check-in%20summary%20for%20website.md

**Comment by sstrassberg** [comment]
@kbnammacher-usds @wslack Can have a look at the file and let me know if you think this is the right format for the results page on the website? You can also make PRs on the content if you want.

**Comment by wslack** [comment]
See PR 323 in the other repo!

**Comment by sstrassberg** [comment]
https://github.com/usds/SME-QA/blob/main/user_research/reports/six-month%20check-in%20summary%20for%20website.md
