### ISSUE TITLE
fix sidenav child->child padding

### ISSUE THREAD

**Issue by bendelphine** [usds/SME-QA-Website#347]
related issue at https://github.com/uswds/uswds/issues/3967

**Comment by bendelphine** [comment]
pull #348 should take us from this:

![Screen Shot 2021-04-26 at 4 49 54 PM](https://user-images.githubusercontent.com/77686273/116155940-70b07700-a6b0-11eb-8a6d-8b2c60e92c15.png)

to this:

![Screen Shot 2021-04-26 at 4 51 42 PM](https://user-images.githubusercontent.com/77686273/116155987-83c34700-a6b0-11eb-9b88-3d5c677f840a.png)

if that works, we can also add a bit more padding to the left, possibly reduce the font size a slight bit as well for differentiating the levels.

**Comment by stephaniefaith** [comment]
@bendelphine Yes ! That works!! Do you need me to approve the PR?

**Comment by bendelphine** [comment]
@stephaniefaith yes! just ping me on slack after
