### ISSUE TITLE
Fix 404 pages

### ISSUE THREAD

**Issue by mgifford** [usds/SME-QA-Website#375]
# Bug Report

There are links to these URLs which all go to 404 pages:

- https://smeqa.usds.gov/info/cx-govwide/privacy/target=%22_blank%22 1
- https://smeqa.usds.gov/info/data-govwide/privacy/target=%22_blank%22 1
- https://smeqa.usds.gov/results/round-two/cms/ 1
- https://smeqa.usds.gov/results/round-two/epa/ 1
- https://smeqa.usds.gov/results/round-two/gsa/ 1
- https://smeqa.usds.gov/results/round-two/state/ 1

These should be fixed and you should have a 404 page like the others - https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site

**Comment by wslack** [comment]
We have a working 404 now!
