### ISSUE TITLE
Add shared PD and competency library

### ISSUE THREAD

**Issue by humancompanion-usds** [usds/SME-QA-Website#47]
Moving issue https://github.com/usds/SME-QA/issues/629 to this repo. 

We agreed there that we need a new section of the site, or just additions to the toolkits, that has shared PDs and competencies, in markdown form, and proficiency levels but with no indication of which level is required (that's the secret sauce).

**Comment by humancompanion-usds** [comment]
Add GSA as well.

**Comment by humancompanion-usds** [comment]
Start with competencies then we'll move onto PDs.

**Comment by 0kl-usds** [comment]
@sharmaneil @humancompanion @stephaniefaith meet on this

**Comment by 0kl-usds** [comment]
re: https://github.com/usds/SME-QA/wiki/Policy-Call-Notes
> Wait until the GSA is past all their assessment stuff.

As I understood the call, we cannot post GSA competencies and levels on the site until after they are finished

**Comment by humancompanion-usds** [comment]
[Sample Competency Descriptions (1).docx](https://github.com/usds/SME-QA-Website/files/3810138/Sample.Competency.Descriptions.1.docx)
 From @stephaniefaith

**Comment by humancompanion-usds** [comment]
@sstrassberg is working on the interview question portion of this.

**Comment by sstrassberg** [comment]
[Creating Structured Interview Questions:Breadth and Depth.pdf](https://github.com/usds/SME-QA-Website/files/3838050/Creating.Structured.Interview.Questions.Breadth.and.Depth.pdf)

**Comment by humancompanion-usds** [comment]
* [ ] Add pilot competencies and proficiency levels to the Word doc

**Comment by humancompanion-usds** [comment]
@wslack filed issue #92 so I'm going to close this as that was the remaining task.
