### ISSUE TITLE
More information

### ISSUE THREAD

**Issue by jennmalcolm** [usds/SME-QA-Website#5]
## Tell us about yourself

* Name: Jennifer Malcolm
* Email address: jennifer.malcolm@onrr.gov
* Phone number: 202-208-3938
* Department: DOI
* Agency:
* Office: Office of Natural Resources Revenue

## Describe your hiring situation

* Series you are trying to hire into? 0301, Innovation Specialist
* Grade level you are trying to hire for? GS-13
* Number of vacancies you have approval to hire for?

**Comment by humancompanion-usds** [comment]
@jennmalcolm - Apologies for the delay. Someone will be getting back to you shortly.

**Comment by humancompanion-usds** [comment]
We sent a follow up email back in August. Closing this out.
