### ISSUE TITLE
Write and decide how to present SME Resume Review instructions

### ISSUE THREAD

**Issue by humancompanion-usds** [usds/SME-QA-Website#62]
audience: SMEs (vs HR audience where we have SOPs Kelvin is finalizing)
On the site we have a placeholder for SME Resume Review instructions:

https://smeqa.usds.gov/hiring-phases/reviewing-resumes/sme-instructions/

However, we've not written those instructions yet. This task is to write those instructions. Once they are written I can put them into the toolkit.

I did write some up for our tool, but that presumes that folks have out tool which is an unknown at the moment. Thus we may need to give some other instructions.

**Comment by humancompanion-usds** [comment]
This is more about updating the resume review related slides for the SME training to not mention USAS and 1-3 sentences.

**Comment by stephaniefaith** [comment]
@humancompanion agreed- this is super critical for us to decide pretty immediately how we are going to present this in the Nov 25/26 training: as 1-3 sentences in the TAS vs using  excel vs using a web app; or presenting all three and giving agencies the choice to decide once they get to that point.

**Comment by humancompanion-usds** [comment]
Our plan is to do the following in the training next week:

* Determine the technology for review
  * Show the tool
    * We will customize the tool for you
    * What problems the webapp will solve: 1-3 sentences, easier review (lessons learned)
  * Explain two other options:
    * Use talent acq system, that was hard in USA Staffing
    * Use word/excel; we have some templates-in-progress

I'm closing this issue and opening new issues for posting SOPs for SMEs for USAS and Monster.
