### ISSUE TITLE
Remove assessment strategy phase and put it under Job analysis

### ISSUE THREAD

**Issue by stephaniefaith** [usds/SME-QA-Website#71]
Move this
https://smeqa.usds.gov/hiring-phases/assessment-strategy/

to the job analysis section

**Comment by humancompanion-usds** [comment]
What is the goal of this change?

**Comment by humancompanion-usds** [comment]
2 immediate concerns:
* We'd have to combine the toolkits of both sections, which both contain 6 items.
* The exceptions on the assessment strategy page are fairly critical. Combining them into an already heavy job analysis workshop section is going to further diminish their importance.

**Comment by humancompanion-usds** [comment]
I believe @stephaniefaith acquiesced yesterday to not removing the Assessment Strategy phase and instead we're actively revising the toolkit in issue #130. Thus closing this.
