### ISSUE TITLE
Website updates from training prep

### ISSUE THREAD

**Issue by wslack** [usds/SME-QA-Website#73]
## Top level

- [ ] Add a section describing the problems that SME-QA is solving:
  - Unqualified people are making it onto cert lists
  - Entire cert lists are being untested
  - Giant resumes can't be evaluated by people
  - Etc etc.

- [ ] Add a section at the top level describing the impact that SME-QA seeks to have

## Job Analysis Workshop
 - [ ] Rename the section on documenting the assessment strategy so that its clearly distinguished between the section
 - [ ] Add example of proficiency levels

## Job Announcement 
 - [ ] Delete pages on writing the job announcement, focus more on the two examples we have
 - [ ] Setting up the assessment in the TAS - add something back in about this

## Reviewing Resumes
- [ ] Add this text in "HR Role in SME-QA"

> HR is not required to conduct a separate minimum qualifications review for this hiring process. HR’s role is to work with SMEs in setting the assessment criteria, train the SMEs on resume review and interviews, review the notes from SME resume review and interviews to make sure they are using the pre-determined criteria, and make sure anyone deemed not qualified has an associated technical reason given by the SME during the review.  When the SMEs have identified the applicants that achieved an overall passing score from the interviews, HR will still not conduct a separate minimum qualification review. The entire process depended on SMEs being able to use their expertise to assess if an applicant was truly qualified before the applicant would be considered minimally qualified and eligible for veterans preference. Once the remaining applicants are found to meet the qualifications, HR will then adjudicate and apply veterans preference for the first time.  HR will then issue the certificate of eligibles of the "Best Qualified" category to the HM.

- [ ] Add something about personal relationships in training section

## Issuing a certificate
 - [ ] Strike the rating guide from preference adjudication

**Comment by humancompanion-usds** [comment]
I'm not sure I know what these two items are:

1. Replace the "results so far" section with new PDFs about DOI and HHS
We did just update those pages and Stephanie reviewed. The data from the PDFs are reflected there. My understanding was that nothing else from the Case Study/Lessons Learned document is cleared and thus cannot move to the web site.

2. Add more information about collecting baseline data
This too we just updated not even a week ago and both Stephanie and Neil reviewed. I don't know what else we want to say there.

The rest I think I can follow and will discuss with Stephanie the goals around the Assessment Strategy changes noted here and in issue #71

**Comment by wslack** [comment]
> We did just update those pages and Stephanie reviewed.

That might have been a note to update the papers in the packet (which I think Shane did) so we can ignore

> Add more information about collecting baseline data

I think this was showing examples of baseline data - not more explanation, but adding to the toolkit. Like "what does baseline data look like" so folks have a template. But, I could be remembering wrong, and if we don't have that and don't plan to, am ok with cutting.

**Comment by humancompanion-usds** [comment]
Noted. 

We do have baseline data, but we cannot share it. It's considered agency data and we were only able to see it once USAS had confirmation from the agencies. That said, we did have a spreadsheet that perhaps we could setup to be a template. But that's a larger lift and should be a distinct issue (i.e. I'd want to assign Neil to do that)

**Comment by wslack** [comment]
ok - do you want me to make that or is it the sort of thing that we should talk about as a group first before I make the issue? (Still learning Github norms)

**Comment by humancompanion-usds** [comment]
The Excel spreadsheet is issue #75

**Comment by humancompanion-usds** [comment]
Okay, I broke this issue out into several to track the changes independently. The stuff I left behind are items I would prefer we do some research on before adding/changing.

**Comment by humancompanion-usds** [comment]
This is now handled by individual issues.
