### ISSUE TITLE
Email to send to SMEs to set expectations

### ISSUE THREAD

**Issue by humancompanion-usds** [usds/SME-QA-Website#79]
@stephaniefaith  is working on this in another issue

**Comment by humancompanion-usds** [comment]
@stephaniefaith - Punt this over to me once you have the content for this email.

**Comment by humancompanion-usds** [comment]
@stephaniefaith - Is this issue a duplicate of this one?
https://github.com/usds/SME-QA-Website/issues/111

It created this email template:
https://smeqa.usds.gov/toolkit/getting-started/sme-recruitment-email/

**Comment by stephaniefaith** [comment]
it's done! on the website.
