### ISSUE TITLE
Add SOP for HR for USAS to setup vacancy and announcement

### ISSUE THREAD

**Issue by humancompanion-usds** [usds/SME-QA-Website#86]
Forthcoming SOP from Kelvin on how HR can setup their vacancy and announcement. It may be that I contribute here too based on my document on creating a JOA per TAS.

**Comment by humancompanion-usds** [comment]
@0kl-usds - Is this SOP forthcoming? I know you were working on it. Just wondering if Jenn R's videos supersede the SOP?

For my reference, the video links are:
* https://opmhrs.adobeconnect.com/poiivp8seqzp
* https://opmhrs.adobeconnect.com/pbcmiw393sj2

**Comment by stephaniefaith** [comment]
closing- this is on our website https://smeqa.usds.gov/hiring-phases/job-announcement/configuring-usas/
