### ISSUE TITLE
Update job analysis presentations

### ISSUE THREAD

**Issue by humancompanion-usds** [usds/SME-QA-Website#88]
# Bug Report

All of the items added in https://github.com/usds/SME-QA-Website/pull/39 need to be verified against what is in the SME-QA archive repo.

* [x] URGENT: Before Monday post the correct job analysis workshop template presentations
* [x] URGENT: Before Monday update SME training on resume review with updated bias slides
  * archive/pilot-guides/Training-SME-Resume-Review-1role.pptx
  * archive/pilot-guides/Training-SME-Resume-Review-Multirole.pptx
* [x] URGENT: Before Monday post the correct phone interview training template
* [x] Verify that the other items in that pull request are the most up-to-date versions

## What happened

The Job Analysis Workshop templates that Martha posted in this issue https://github.com/usds/SME-QA/issues/446 did not make it into this pull request https://github.com/usds/SME-QA-Website/pull/39 (somehow). 

## What I expected to happen

The job analysis template ppts had no presenter notes which tipped us off that they were amiss.

**Comment by wslack** [comment]
added a reference to the phone interview training template to the top message

**Comment by humancompanion-usds** [comment]
@wslack - I'm not sure what you mean by top message. The toolkit section? There is already a link to the Phone Interview Template on the Phone Assessment Interview page (it's the 3rd link, a Word doc). Also, is that the page you intended? This issues spans a few presentations now across the site so not sure which page we're talking about.
