### ISSUE TITLE
Add Steve's slide about the lift for SMEs to the website

### ISSUE THREAD

**Issue by wslack** [usds/SME-QA-Website#90]
(This came up in the training practice - we will be using the slide's contents so it should be on the website)

Originally, I wrote this down as Stephanie's slide to find but I think we tracked it down yesterday.

**Comment by humancompanion-usds** [comment]
I just did this a few minutes ago. Shane had requested it here:
https://github.com/usds/SME-QA/issues/476#issuecomment-555694444

https://smeqa.usds.gov/hiring-phases/getting-started/time-commitment/
