### ISSUE TITLE
Add to website: information about all of the roles involved in SME-QA and the expected hours needed from each role

### ISSUE THREAD

**Issue by wslack** [usds/SME-QA-Website#91]
replaces https://github.com/usds/SME-QA/issues/1019

**Comment by sstrassberg** [comment]
[Pilot Time Comitment (Add to Website).pdf](https://github.com/usds/SME-QA-Website/files/3870950/Pilot.Time.Comitment.Add.to.Website.pdf)
@wslack I believe this is what this issue refers to, correct?

**Comment by humancompanion-usds** [comment]
Yeah, we just created: 
https://smeqa.usds.gov/hiring-phases/getting-started/time-commitment/

Also see my comments here: 
https://github.com/usds/SME-QA/issues/476#issuecomment-555815371

To be clear, at the top of each phase we give a time estimate and list the roles involved. Granted, the time estimates are not per-role. We could do that and add some visualization there. But not for Monday.

**Comment by wslack** [comment]
This is what we needed. I'm moving this to "for review" unless we just want to close.
