### ISSUE TITLE
Add to website: recommendation that resume review training should be three hours

### ISSUE THREAD

**Issue by wslack** [usds/SME-QA-Website#97]

**Comment by humancompanion-usds** [comment]
I just grepped across the entire site and the only instance of "2 hours" I found was on the new page we just created and it was in reference to the time Interview training takes:

> Resume review training (3 hours) and Interview training (2 hours)

Do we know where we're making an incorrect recommendation?

**Comment by wslack** [comment]
I don't! Maybe the issue was that we didn't have a suggested time on the old set of pages?

**Comment by humancompanion-usds** [comment]
Yeah. Agreed. This is therefore fixed. Closing.
