### ISSUE TITLE
Add information about tiebreaker procedures to the website from SOP work

### ISSUE THREAD

**Issue by wslack** [usds/SME-QA-Website#98]
https://github.com/usds/SME-QA-Website/tree/master/pages/phases/reviewing-resumes should have something about tiebreaking

**Comment by JennNoinaj** [comment]
updated https://smeqa.usds.gov/hiring-phases/reviewing-resumes/ and https://smeqa.usds.gov/hiring-phases/reviewing-resumes/prep/
